/**
 * geo-cc-map.generated.ts
 * ⚠️  自動生成ファイル — 手動編集禁止
 *
 * 生成元: docs/spec/cc-mapping.md
 * 生成日: 2026-04-15T03:08:27.901Z
 * 生成コマンド: pnpm gen:types
 *
 * pluginId + paramId → CC番号・min/max を実行時に参照するための定数マップ。
 * Sequencer / LFO でハードコードを避けるために使う。
 */

import type { GeoParamMap } from './geo-types.generated'

export const GEO_CC_MAP = {
  'icosphere': {
    'radius': {
      ccNumber: 11101,
      pluginMin: 0.5,
      pluginMax: 10,
      block: 'EXISTENCE',
      blockName: 'Primary Amount',
    },
    'detail': {
      ccNumber: 11201,
      pluginMin: 0,
      pluginMax: 5,
      block: 'FORM',
      blockName: 'Density/Detail',
    },
    'speed': {
      ccNumber: 11301,
      pluginMin: 0,
      pluginMax: 2,
      block: 'MOTION',
      blockName: 'Temporal Speed',
    },
    'hue': {
      ccNumber: 11401,
      pluginMin: 0,
      pluginMax: 360,
      block: 'COLOR',
      blockName: 'Hue',
    },
  },
  'torus': {
    'radius': {
      ccNumber: 11101,
      pluginMin: 0.5,
      pluginMax: 10,
      block: 'EXISTENCE',
      blockName: 'Primary Amount',
    },
    'tube': {
      ccNumber: 11102,
      pluginMin: 0.1,
      pluginMax: 4,
      block: 'EXISTENCE',
      blockName: 'Secondary Amount',
    },
    'tubularSegs': {
      ccNumber: 11201,
      pluginMin: 8,
      pluginMax: 256,
      block: 'FORM',
      blockName: 'Density/Detail',
    },
    'radialSegs': {
      ccNumber: 11202,
      pluginMin: 3,
      pluginMax: 64,
      block: 'FORM',
      blockName: 'Inner Shape',
    },
    'speed': {
      ccNumber: 11301,
      pluginMin: 0,
      pluginMax: 2,
      block: 'MOTION',
      blockName: 'Temporal Speed',
    },
    'hue': {
      ccNumber: 11401,
      pluginMin: 0,
      pluginMax: 360,
      block: 'COLOR',
      blockName: 'Hue',
    },
  },
  'torusknot': {
    'radius': {
      ccNumber: 11101,
      pluginMin: 0.5,
      pluginMax: 8,
      block: 'EXISTENCE',
      blockName: 'Primary Amount',
    },
    'tube': {
      ccNumber: 11102,
      pluginMin: 0.1,
      pluginMax: 2,
      block: 'EXISTENCE',
      blockName: 'Secondary Amount',
    },
    'tubularSegs': {
      ccNumber: 11201,
      pluginMin: 32,
      pluginMax: 512,
      block: 'FORM',
      blockName: 'Density/Detail',
    },
    'radialSegs': {
      ccNumber: 11202,
      pluginMin: 3,
      pluginMax: 32,
      block: 'FORM',
      blockName: 'Inner Shape',
    },
    'p': {
      ccNumber: 11203,
      pluginMin: 1,
      pluginMax: 8,
      block: 'FORM',
      blockName: 'Topology A',
    },
    'q': {
      ccNumber: 11204,
      pluginMin: 1,
      pluginMax: 8,
      block: 'FORM',
      blockName: 'Topology B',
    },
    'speed': {
      ccNumber: 11301,
      pluginMin: 0,
      pluginMax: 2,
      block: 'MOTION',
      blockName: 'Temporal Speed',
    },
    'hue': {
      ccNumber: 11401,
      pluginMin: 0,
      pluginMax: 360,
      block: 'COLOR',
      blockName: 'Hue',
    },
  },
  'contour': {
    'size': {
      ccNumber: 11101,
      pluginMin: 10,
      pluginMax: 500,
      block: 'EXISTENCE',
      blockName: 'Primary Amount',
    },
    'segments': {
      ccNumber: 11201,
      pluginMin: 10,
      pluginMax: 150,
      block: 'FORM',
      blockName: 'Density/Detail',
    },
    'speed': {
      ccNumber: 11301,
      pluginMin: 0,
      pluginMax: 2,
      block: 'MOTION',
      blockName: 'Temporal Speed',
    },
    'amplitude': {
      ccNumber: 11302,
      pluginMin: 0.1,
      pluginMax: 8,
      block: 'MOTION',
      blockName: 'Deformation',
    },
    'scale': {
      ccNumber: 11303,
      pluginMin: 0.1,
      pluginMax: 2,
      block: 'MOTION',
      blockName: 'Frequency',
    },
    'hue': {
      ccNumber: 11401,
      pluginMin: 0,
      pluginMax: 360,
      block: 'COLOR',
      blockName: 'Hue',
    },
  },
  'hex-grid': {
    'hexSize': {
      ccNumber: 11101,
      pluginMin: 0.5,
      pluginMax: 5,
      block: 'EXISTENCE',
      blockName: 'Primary Amount',
    },
    'cols': {
      ccNumber: 11201,
      pluginMin: 4,
      pluginMax: 30,
      block: 'FORM',
      blockName: 'Density/Detail',
    },
    'rows': {
      ccNumber: 11202,
      pluginMin: 4,
      pluginMax: 30,
      block: 'FORM',
      blockName: 'Inner Shape',
    },
    'speed': {
      ccNumber: 11301,
      pluginMin: 0,
      pluginMax: 2,
      block: 'MOTION',
      blockName: 'Temporal Speed',
    },
    'maxHeight': {
      ccNumber: 11302,
      pluginMin: 0,
      pluginMax: 10,
      block: 'MOTION',
      blockName: 'Deformation',
    },
    'hue': {
      ccNumber: 11401,
      pluginMin: 0,
      pluginMax: 360,
      block: 'COLOR',
      blockName: 'Hue',
    },
  },
  'grid-tunnel': {
    'radius': {
      ccNumber: 11101,
      pluginMin: 1,
      pluginMax: 10,
      block: 'EXISTENCE',
      blockName: 'Primary Amount',
    },
    'segments': {
      ccNumber: 11201,
      pluginMin: 3,
      pluginMax: 24,
      block: 'FORM',
      blockName: 'Density/Detail',
    },
    'rings': {
      ccNumber: 11202,
      pluginMin: 5,
      pluginMax: 40,
      block: 'FORM',
      blockName: 'Inner Shape',
    },
    'speed': {
      ccNumber: 11301,
      pluginMin: 0,
      pluginMax: 3,
      block: 'MOTION',
      blockName: 'Temporal Speed',
    },
    'length': {
      ccNumber: 11501,
      pluginMin: 10,
      pluginMax: 100,
      block: 'SPACE',
      blockName: 'Depth',
    },
    'hue': {
      ccNumber: 11401,
      pluginMin: 0,
      pluginMax: 360,
      block: 'COLOR',
      blockName: 'Hue',
    },
  },
  'grid-wave': {
    'size': {
      ccNumber: 11101,
      pluginMin: 1,
      pluginMax: 500,
      block: 'EXISTENCE',
      blockName: 'Primary Amount',
    },
    'segments': {
      ccNumber: 11201,
      pluginMin: 10,
      pluginMax: 100,
      block: 'FORM',
      blockName: 'Density/Detail',
    },
    'speed': {
      ccNumber: 11301,
      pluginMin: 0.1,
      pluginMax: 2,
      block: 'MOTION',
      blockName: 'Temporal Speed',
    },
    'amplitude': {
      ccNumber: 11302,
      pluginMin: 0.1,
      pluginMax: 2,
      block: 'MOTION',
      blockName: 'Deformation',
    },
    'frequency': {
      ccNumber: 11303,
      pluginMin: 0.1,
      pluginMax: 1,
      block: 'MOTION',
      blockName: 'Frequency',
    },
    'hue': {
      ccNumber: 11401,
      pluginMin: 0,
      pluginMax: 360,
      block: 'COLOR',
      blockName: 'Hue',
    },
    'posX': {
      ccNumber: 12501,
      pluginMin: -50,
      pluginMax: 50,
      block: 'SPACE',
      blockName: 'Position X',
    },
    'posY': {
      ccNumber: 12502,
      pluginMin: -50,
      pluginMax: 50,
      block: 'SPACE',
      blockName: 'Position Y',
    },
    'posZ': {
      ccNumber: 12503,
      pluginMin: -50,
      pluginMax: 50,
      block: 'SPACE',
      blockName: 'Position Z',
    },
    'lookAtX': {
      ccNumber: 12504,
      pluginMin: -50,
      pluginMax: 50,
      block: 'SPACE',
      blockName: 'LookAt X',
    },
    'lookAtY': {
      ccNumber: 12505,
      pluginMin: -50,
      pluginMax: 50,
      block: 'SPACE',
      blockName: 'LookAt Y',
    },
    'lookAtZ': {
      ccNumber: 12506,
      pluginMin: -50,
      pluginMax: 50,
      block: 'SPACE',
      blockName: 'LookAt Z',
    },
    'radius': {
      ccNumber: 12101,
      pluginMin: 1,
      pluginMax: 50,
      block: 'EXISTENCE',
      blockName: 'Primary Amount',
    },
    'autoRotate': {
      ccNumber: 12102,
      pluginMin: 0,
      pluginMax: 1,
      block: 'EXISTENCE',
      blockName: 'Auto Rotate',
    },
    'height': {
      ccNumber: 12502,
      pluginMin: -20,
      pluginMax: 30,
      block: 'SPACE',
      blockName: 'Position Y',
    },
  },
  'bloom': {
    'strength': {
      ccNumber: 14101,
      pluginMin: 0,
      pluginMax: 3,
      block: 'EXISTENCE',
      blockName: 'Primary Amount',
    },
    'radius': {
      ccNumber: 14603,
      pluginMin: 0,
      pluginMax: 1,
      block: 'EDGE',
      blockName: 'Sharpness/Blur',
    },
    'threshold': {
      ccNumber: 14701,
      pluginMin: 0,
      pluginMax: 1,
      block: 'BLEND',
      blockName: 'Blend Amount',
    },
  },
  'after-image': {
    'damp': {
      ccNumber: 14702,
      pluginMin: 0,
      pluginMax: 1,
      block: 'BLEND',
      blockName: 'Feedback Amount',
    },
  },
  'feedback': {
    'amount': {
      ccNumber: 14702,
      pluginMin: 0,
      pluginMax: 0.95,
      block: 'BLEND',
      blockName: 'Feedback Amount',
    },
    'decay': {
      ccNumber: 14703,
      pluginMin: 0.9,
      pluginMax: 1,
      block: 'BLEND',
      blockName: 'Feedback Scale',
    },
    'offsetX': {
      ccNumber: 14501,
      pluginMin: -0.05,
      pluginMax: 0.05,
      block: 'SPACE',
      blockName: 'Position X',
    },
    'offsetY': {
      ccNumber: 14502,
      pluginMin: -0.05,
      pluginMax: 0.05,
      block: 'SPACE',
      blockName: 'Position Y',
    },
  },
  'color-grading': {
    'saturation': {
      ccNumber: 14401,
      pluginMin: 0,
      pluginMax: 2,
      block: 'COLOR',
      blockName: 'Saturation',
    },
    'brightness': {
      ccNumber: 14402,
      pluginMin: 0,
      pluginMax: 2,
      block: 'COLOR',
      blockName: 'Brightness',
    },
    'contrast': {
      ccNumber: 14403,
      pluginMin: 0,
      pluginMax: 2,
      block: 'COLOR',
      blockName: 'Contrast',
    },
  },
  'glitch': {
    'goWild': {
      ccNumber: 14101,
      pluginMin: 0,
      pluginMax: 1,
      block: 'EXISTENCE',
      blockName: 'Primary Amount',
    },
    'interval': {
      ccNumber: 14302,
      pluginMin: 10,
      pluginMax: 240,
      block: 'MOTION',
      blockName: 'Randomness',
    },
  },
  'kaleidoscope': {
    'segments': {
      ccNumber: 14201,
      pluginMin: 2,
      pluginMax: 16,
      block: 'FORM',
      blockName: 'Symmetry/Repeat',
    },
    'angle': {
      ccNumber: 14301,
      pluginMin: 0,
      pluginMax: 6.28,
      block: 'MOTION',
      blockName: 'Phase/Offset',
    },
  },
  'rgb-shift': {
    'amount': {
      ccNumber: 14101,
      pluginMin: 0,
      pluginMax: 0.05,
      block: 'EXISTENCE',
      blockName: 'Primary Amount',
    },
    'angle': {
      ccNumber: 14301,
      pluginMin: 0,
      pluginMax: 6.28,
      block: 'MOTION',
      blockName: 'Phase/Offset',
    },
  },
  'zoom-blur': {
    'strength': {
      ccNumber: 14101,
      pluginMin: 0,
      pluginMax: 2,
      block: 'EXISTENCE',
      blockName: 'Primary Amount',
    },
  },
  'mirror': {
    'horizontal': {
      ccNumber: 14201,
      pluginMin: 0,
      pluginMax: 1,
      block: 'FORM',
      blockName: 'Symmetry/Repeat',
    },
  },
  'crt': {
    'scanlineIntensity': {
      ccNumber: 14601,
      pluginMin: 0,
      pluginMax: 1,
      block: 'EDGE',
      blockName: 'Edge Strength',
    },
    'curvature': {
      ccNumber: 14604,
      pluginMin: 0,
      pluginMax: 0.5,
      block: 'EDGE',
      blockName: 'Vignette',
    },
  },
  'film': {
    'intensity': {
      ccNumber: 14101,
      pluginMin: 0,
      pluginMax: 1,
      block: 'EXISTENCE',
      blockName: 'Primary Amount',
    },
    'grayscale': {
      ccNumber: 14401,
      pluginMin: 0,
      pluginMax: 1,
      block: 'COLOR',
      blockName: 'Saturation',
    },
  },
  'frei-chen': {
    'width': {
      ccNumber: 14601,
      pluginMin: 64,
      pluginMax: 1920,
      block: 'EDGE',
      blockName: 'Edge Strength',
    },
    'height': {
      ccNumber: 14602,
      pluginMin: 64,
      pluginMax: 1080,
      block: 'EDGE',
      blockName: 'Edge Thickness',
    },
  },
  'starfield': {
    'size': {
      ccNumber: 13101,
      pluginMin: 0.01,
      pluginMax: 0.3,
      block: 'EXISTENCE',
      blockName: 'Primary Amount',
    },
    'opacity': {
      ccNumber: 13102,
      pluginMin: 0,
      pluginMax: 1,
      block: 'EXISTENCE',
      blockName: 'Opacity',
    },
    'count': {
      ccNumber: 13201,
      pluginMin: 500,
      pluginMax: 10000,
      block: 'FORM',
      blockName: 'Density/Detail',
    },
    'speed': {
      ccNumber: 13301,
      pluginMin: 0,
      pluginMax: 2,
      block: 'MOTION',
      blockName: 'Temporal Speed',
    },
    'depth': {
      ccNumber: 13501,
      pluginMin: 10,
      pluginMax: 200,
      block: 'SPACE',
      blockName: 'Depth',
    },
  },
} satisfies GeoParamMap
